api_version = "2025-10"
[[extensions]]
name = "t:name"
handle = "product-configuration"
type = "ui_extension"
uid = "1417fe2d-35ff-0a3a-ce8e-5402c29d5028ba17097d"

# Both extension points are required
[[extensions.targeting]]
module = "./src/ProductDetailsConfigurationExtension.jsx"
target = "admin.product-details.configuration.render"
[extensions.targeting.urls]
edit = "/bundles/products/{product_id}"


[[extensions.targeting]]
module = "./src/ProductVariantDetailsConfigurationExtension.jsx"
# The target used here must match the target used in the module file (./src/ProductVariantDetailsConfigurationExtension.jsx)
target = "admin.product-variant-details.configuration.render"
